import { StyleSheet } from 'react-native';
import { SH, SW, SF } from '../../utils/Dimensions';
import Colors from '../../utils/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: SF(22),
    fontFamily: 'Poppins-Bold',
    marginTop: SH(15),
    color: '#333',
  },
  message: {
    fontSize: SF(16),
    marginTop: SH(8),
    textAlign: 'center',
    color: '#666',
    lineHeight: SH(22),
  },
  righticons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topContainer: {
    marginBottom: SH(20),
  },

  image: {
    width: SW(350), height: SH(270), borderRadius: 10, resizeMode: 'cover',
  },
  verifiedContainer: {
    position: 'absolute',
    top: SH(255),
    left: SW(228),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e3e6e4',
    paddingHorizontal: SW(5),
    paddingVertical: SW(3),
    borderRadius: 5,
    alignSelf: 'flex-end',
    width: SW(130),
  },
  verifiedBadge: {
    width: SW(20),
    height: SH(20),
    paddingHorizontal: SW(1),
    resizeMode: 'contain',
  },
  verifiedText: {
    color: 'green',
    fontFamily: 'Poppins-Regular',
    fontSize: SF(13),
    paddingHorizontal: SW(2),
    textTransform: 'capitalize',
  },
  dot: {
    backgroundColor: Colors.light,
  },
  activeDot: {
    backgroundColor: Colors.light,
  },
  flexContainer1: {
    // flexDirection: "row",
    // flexWrap: "wrap",
    // justifyContent: "space-between",
    // paddingHorizontal: SW(10),
    // paddingVertical: SH(10),
    // // borderColor: Colors.gray,
    // // borderWidth: 1,
    // borderRadius: 10,
    // width: "100%",
    // marginVertical: SH(5),
    // shadowColor: '#000',
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.1,
    // shadowRadius: 5,
    // elevation: 5,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: SW(8),
    paddingVertical: SH(10),
    borderRadius: 10,
    width: '99%',
    marginVertical: SH(5),
    backgroundColor: '#fff', // Ensure background for shadow to show properly
    marginHorizontal: SW(2),
    // Updated shadow
    shadowColor: Colors.theme_color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  familyDiv: {
    paddingHorizontal: SW(8),
    paddingVertical: SH(10),
    borderRadius: 10,
    width: '99%',
    backgroundColor: '#fff', // Ensure background for shadow to show properly
    marginHorizontal: SW(2),
    // Updated shadow
    shadowColor: Colors.theme_color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    marginVertical: SH(5),
  },

  detailbox: {
    paddingHorizontal: SW(10),
    paddingVertical: SH(10),
    shadowColor: Colors.theme_color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderRadius: 10,
    width: '99%',
    marginVertical: SH(5),
    backgroundColor: '#fff',
  },

  leftContainer: {
    width: '52%',
    marginBottom: SH(10),
  },

  rightContainer: {
    width: '48%',
    paddingTop: SH(22),
    paddingLeft: SW(5),
    alignSelf: 'flex-start',
  },

  HeadingText: {
    fontSize: SF(15),
    fontFamily: 'Poppins-Bold',
    textTransform: 'capitalize',
    lineHeight: SF(18),
    paddingTop: SH(2),
  },

  text: {
    fontfamily: 'Poppins-Regular',
    color: '#000',
    fontSize: SF(14),
  },

  flexContainer: {
    paddingHorizontal: SW(10),
    paddingVertical: SH(10),
    shadowColor: Colors.theme_color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderRadius: 10,
    backgroundColor: '#fff',
    width: '99%',
    marginTop:SH(8)
  },
  flex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginRight: SW(5),
  },
  toptext: {
    fontSize: SF(10),
    fontFamily: 'Poppins-Regular',
    textTransform: 'capitalize',
  },
  Idtext: {
    fontSize: SF(12),
    fontFamily: 'Poppins-Bold',
    color: Colors.dark,
  },
  flexContainer2: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',

  },
  sharecontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: SW(3),
    paddingVertical: SH(3),
    backgroundColor: Colors.light,
    marginTop: SH(5),
  },
  iconContainer: {
    alignItems: 'center',
  },
  iconText: {
    fontSize: SF(12),
    color: Colors.theme_color,
    marginTop: SH(5),
    textTransform: 'capitalize',
  },
  interestedButton: {
    backgroundColor: Colors.theme_color,
    paddingHorizontal: SW(20),
    paddingVertical: SH(3),
    borderRadius: 8,
  },
  buttonText: {
    color: Colors.light,
    fontFamily: 'Poppins-Medium',
    fontSize: SF(12),
    textTransform: 'capitalize',

  },
  ButtonText: {
    color: Colors.light,
    fontFamily: 'Poppins-Bold',
    fontSize: SF(12),
    textAlign: 'center',
    backgroundColor: Colors.theme_color,
    paddingVertical: SH(5),
    marginTop: SH(10),
    borderRadius: 10,
    marginHorizontal: SW(90),
    textTransform: 'capitalize',
  },
  smallImage: {
    width: SW(80),
    height: SH(85),
    resizeMode: 'cover',
    borderRadius: 50,
  },
  flexContainer3: {
    shadowColor: Colors.theme_color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: SH(5),
    paddingHorizontal: SW(10),
    paddingVertical: SH(10),
    width: '99%',
  },
  flexContainer4: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    flex: 1,
    textTransform: 'capitalize',
  },
  icon: {
    fontSize: SF(20),
  },
  checkIcon: {
    color: 'green',
  },
  crossIcon: {
    color: 'red',
  },
  flexContainer5: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SW(10),
    paddingVertical: SH(10),
  },
  bottomContainer: {
    paddingVertical: SH(10),
    paddingHorizontal: SW(10),
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: 'gray',
    borderWidth: 1,
  },
  declineButton: {
    backgroundColor: '#c10007',
    paddingVertical: SH(7),
    paddingHorizontal: SH(40),
    borderRadius: 50,
    marginHorizontal: SW(10),
    display: 'flex',
    flexDirection: 'row',
  },
  declineButtonText: {
    color: '#fff',
    fontFamily: 'Poppins-Regular',
    fontSize: SF(15),
    marginHorizontal: SW(5),
  },
  acceptButton: {
    backgroundColor: '#008236',
    paddingVertical: SH(7),
    paddingHorizontal: SH(40),
    borderRadius: 50,
    marginHorizontal: SW(10),
    display: 'flex',
    flexDirection: 'row',
  },
  acceptButtonText: {
    color: '#fff', fontFamily: 'Poppins-Regular',
    fontSize: SF(15),
    textTransform: 'capitalize',
  },
  warningText: {
    color: 'red',
    fontSize: SF(14),
    textAlign: 'center',
    marginVertical: SH(10),
    fontFamily: 'Poppins-Bold',
    textTransform: 'capitalize',
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: SH(5),
  },
  infoLabel: {
    width: SW(150),
    fontfamily: 'Poppins-Regular',
    color: '#000',
    fontSize: SF(15),
  },
  infoValue: {
    flex: 1,
    color: '#000',
    flexWrap: 'wrap',
  },
  sliderContainer: {
    marginBottom: SH(30),
    height: SH(290),
  },
  sliderImage: {
    width: '100%',
    height: SH(290),
    resizeMode: 'cover',
  },
});

export default styles;
